# -*- coding: utf-8 -*-
"""مشروع تحليلي.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnTaikEXMwIKrG5ov2KnyR04eLMRQCLk
"""


import pandas as pd
import streamlit as st
import plotly.express as px

# 1. إعدادات الصفحة الأساسية
st.set_page_config(page_title="Smart Mobility & Traffic Safety", layout="wide")

st.title("📊 Smart Mobility & Traffic Safety Dashboard")
st.markdown("لوحة تحكم ذكية لتحليل مسببات الحوادث المرورية بناءً على بيانات الطريق والطقس")

# 2. قراءة ملف البيانات الجديد الخاص بكِ
df = pd.read_csv("train.csv")

# 3. تصميم الشريط الجانبي (Sidebar) للفلاتر بناءً على أعمدتكِ الفعلية
st.sidebar.header("🔍 فلاتر التحكم (Filters)")

# فلتر حالة الطقس (weather)
weather_options = df['weather'].unique()
selected_weather = st.sidebar.multiselect("اختر حالة الطقس:", options=weather_options, default=weather_options)

# فلتر نوع الطريق (road_type)
road_options = df['road_type'].unique()
selected_road = st.sidebar.multiselect("اختر نوع الطريق:", options=road_options, default=road_options)

# تطبيق الفلاتر ديناميكياً على البيانات
filtered_df = df[(df['weather'].isin(selected_weather)) & (df['road_type'].isin(selected_road))]


# 4. عرض المؤشرات الرقمية السريعة (KPIs) بناءً على بياناتكِ
col1, col2, col3 = st.columns(3)
col1.metric("إجمالي الحوادث المحددة", len(filtered_df))
col2.metric("متوسط سرعة الطريق (Speed Limit)", f"{int(filtered_df['speed_limit'].mean())} كم/س")
col3.metric("متوسط نسبة خطر الحادث (Risk)", f"{filtered_df['accident_risk'].mean().round(2)}")

st.markdown("---")

# 5. الرسم البياني الأول: توزيع الحوادث حسب وقت اليوم (بديل الخريطة)
st.subheader("⏰ توزيع مخاطر الحوادث حسب فترات اليوم (Time of Day)")
fig_time = px.histogram(filtered_df, x='time_of_day', y='accident_risk', histfunc='avg',
                        title="Average Accident Risk by Time of Day", color_discrete_sequence=['#E63946'])
st.plotly_chart(fig_time, use_container_width=True)

st.markdown("---")

# 6. الرسومات البيانية التفاعلية للأعمدة الأخرى
col4, col5 = st.columns(2)

with col4:
    st.subheader("🛣️ خطر الحوادث حسب نوع الطريق")
    fig_road = px.box(filtered_df, x='road_type', y='accident_risk', title="Accident Risk Distribution by Road Type", color='road_type')
    st.plotly_chart(fig_road, use_container_width=True)

with col5:
    st.subheader("🌦️ تأثير الطقس على خطورة الحادث")

    fig_weather = px.histogram(filtered_df, x='weather', y='accident_risk', histfunc='avg', title="Average Accident Risk by Weather")
    st.plotly_chart(fig_weather, width='stretch')


# 7. حاسبة تقدير المخاطر الذكية التفاعلية (Interactive Risk Calculator)
st.markdown("---")
st.subheader("🧮 حاسبة تقدير مخاطر الحوادث الذكية (Risk Calculator)")

with st.container():
    # اختيار سرعة الطريق وعمر السائق الافتراضي كـ Sliders
    user_speed = st.slider("السرعة المحددة للطريق (Speed Limit):", int(df['speed_limit'].min()), int(df['speed_limit'].max()), 60)
    user_lighting = st.selectbox("الإضاءة في الطريق (Lighting):", df['lighting'].unique())

    # حساب نتيجة بناءً على المدخلات لإبهار المدربين
    if user_speed > 50 and user_lighting == 'night':
        risk_score = "⚠️ مرتفع جداً (High Risk) - ينصح بزيادة اللوحات الإرشادية وتقليل السرعة ليلاً"
    else:
        risk_score = "✅ طبيعي / منخفض (Low to Moderate Risk)"

    st.info(f"بناءً على السيناريو المختار: مستوى خطر الحادث المتوقع هو: **{risk_score}**")

