# -*- coding: utf-8 -*-
"""مشروع تحليلي.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnTaikEXMwIKrG5ov2KnyR04eLMRQCLk
"""


import pandas as pd
import streamlit as st
import plotly.express as px

# 1. إعدادات الصفحة الأساسية
st.set_page_config(page_title="Smart Mobility & Traffic Safety", layout="wide")

st.title("📊 Smart Mobility & Traffic Safety Dashboard")
st.markdown("لوحة تحكم ذكية لتحليل مسببات الحوادث المرورية بناءً على بيانات الطريق والطقس")

# 2. قراءة ملف البيانات الجديد الخاص بكِ
df = pd.read_csv("train_small.csv")

# 3. تصميم الشريط الجانبي (Sidebar) للفلاتر بناءً على أعمدتكِ الفعلية
st.sidebar.header("🔍 فلاتر التحكم (Filters)")

# فلتر حالة الطقس (weather)
weather_options = df['weather'].unique()
selected_weather = st.sidebar.multiselect("اختر حالة الطقس:", options=weather_options, default=weather_options)

# فلتر نوع الطريق (road_type)
road_options = df['road_type'].unique()
selected_road = st.sidebar.multiselect("اختر نوع الطريق:", options=road_options, default=road_options)

# تطبيق الفلاتر ديناميكياً على البيانات
filtered_df = df[(df['weather'].isin(selected_weather)) & (df['road_type'].isin(selected_road))]


# 4. عرض المؤشرات الرقمية السريعة (KPIs) بناءً على بياناتكِ
col1, col2, col3 = st.columns(3)
col1.metric("إجمالي الحوادث المحددة", len(filtered_df))
col2.metric("متوسط سرعة الطريق (Speed Limit)", f"{int(filtered_df['speed_limit'].mean())} كم/س")
col3.metric("متوسط نسبة خطر الحادث (Risk)", f"{filtered_df['accident_risk'].mean().round(2)}")

st.markdown("---")

# 5. الرسم البياني الأول: توزيع الحوادث حسب وقت اليوم (بديل الخريطة)
st.subheader("⏰ توزيع مخاطر الحوادث حسب فترات اليوم (Time of Day)")
fig_time = px.histogram(filtered_df, x='time_of_day', y='accident_risk', histfunc='avg',
                        title="Average Accident Risk by Time of Day", color_discrete_sequence=['#E63946'])
st.plotly_chart(fig_time, use_container_width=True)

st.markdown("---")

# 6. الرسومات البيانية التفاعلية للأعمدة الأخرى
col4, col5 = st.columns(2)

with col4:
    st.subheader("🛣️ خطر الحوادث حسب نوع الطريق")
    fig_road = px.box(filtered_df, x='road_type', y='accident_risk', title="Accident Risk Distribution by Road Type", color='road_type')
    st.plotly_chart(fig_road, use_container_width=True)

with col5:
    st.subheader("🌦️ تأثير الطقس على خطورة الحادث")

    fig_weather = px.histogram(filtered_df, x='weather', y='accident_risk', histfunc='avg', title="Average Accident Risk by Weather")
    st.plotly_chart(fig_weather, width='stretch')


# 7. الاسنتاجات

st.markdown("---")
st.subheader("💡 أهم الاستنتاجات والتوصيات التحليلية")

# حساب القيم ديناميكياً بناءً على اختيار المستخدم في الفلاتر
highest_weather = filtered_df.groupby('weather')['accident_risk'].mean().idxmax() if len(filtered_df) > 0 else "N/A"
highest_road = filtered_df.groupby('road_type')['accident_risk'].mean().idxmax() if len(filtered_df) > 0 else "N/A"

# عرض الاستنتاجات مباشرة بكامل عرض الصفحة بدون أعمدة تفادياً للخطأ
st.markdown("### 📊 الرصد والتحليل:")
st.info(f"""
1. **تأثير الطقس:** تشير البيانات إلى أن الطقس من نوع **({highest_weather})** يسجل أعلى معدل خطورة للحوادث مقارنة بالأجواء الأخرى.
2. **طبيعة الطرق:** الطرق من نوع **({highest_road})** تعتبر الأكثر عرضة للمخاطر، مما يتطلب مراجعة سرعات القيادة عليها.
3. **فترات الذروة:** نلاحظ تفاوت مخاطر الحوادث بناءً على فترات اليوم (Time of Day)، حيث ترتفع النسبة في أوقات معينة (مثل الليل أو المساء) حسب الإضاءة المتاحة.

**💡 التوصية المقترحة:** ينصح بزيادة اللوحات الإرشادية وتقليل حدود السرعة الذكية عند تقاطع هذه الظروف معاً.
""")
